name: arbify
description: >
  A package providing support for internationalizing
  Flutter applications using intl package with Arbify.
version: 0.0.12
homepage: https://github.com/Arbify/arbify_flutter
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  intl_translation:
    git:
      url: git@github.com:claudiu-mn/intl_translation.git
      ref: 0.18.2
  meta: ^1.1.8
  path: ^1.6.4
  petitparser: ^5.0.0
  universal_io: ^1.0.1
  yaml: ^3.0.0

dev_dependencies:
  lint: ^1.2.0
  mockito: ^5.3.2
  test: ^1.14.7
